### ISSUE TITLE
Open Relay (but restricted)

### ISSUE THREAD

**Issue by Hamsterman** [wader/postfix-relay#16]
I have been trying to build an open relay with restrictions.

So the goal is to have an open relay available for specific hosts in my internal network.
This means that I both want to restrict what host can send emails based on IP-adresses and sender email-adresses (domains maybe). All to avoid spam send from my hosts.

I noticed that when I send a mail from my network (not another docker container) the smtp server sees 172.17.0.1 (docker gateway) as the sender IP and not my host IP (192.168.x.x). So if the mail server only sees the gateway it will be real hard to filter inside the container.

**Comment by wader** [comment]
Hello, mm a bit tricky. Maybe can try using host networking mode with docker? then postfix should get correct source address at least. Alternativly maybe possible to use custom iptables rules for this?

**Comment by Hamsterman** [comment]
I think this is an issue with docker for windows. I can see that others have the same problem where the sources all is the same IP.

I see the same problem in pihole which I using as well.

Since you probably can't fix this issue I will close it.
