### ISSUE TITLE
Question: How to view/enable logging

### ISSUE THREAD

**Issue by Hamsterman** [wader/postfix-relay#19]
I have been looking at the postfix documentation but I have not been able to figure out what to change.

My goal is to view mail logging.
I was hoping to find a file with all failed and successful deliveries.
Also I was hoping to be able to enable full log of the mail aka the full mail as a single file.

**Comment by hemberger** [comment]
You should be able to view the mail logs with `docker logs <container>`. I don't know about logging the message body, but maybe something like [this](https://superuser.com/questions/1081123/how-to-set-up-postfix-to-save-the-message-body-in-the-log-file) will help?

**Comment by Hamsterman** [comment]
Yeah I know - but I was hoping for a single logfile with one line per mail or something like that. Something I could store in a volume. And I am sure it can be done with the content filter as the link you attached. That's a bit more complex for now.

**Comment by wader** [comment]
Close? maybe open a issue if you figure some way to do it but hard to configure with POSTFIX_* env etc
