### ISSUE TITLE
Container keeps stopping

### ISSUE THREAD

**Issue by Hamsterman** [wader/postfix-relay#22]
It seems like the postfix-relay keeps stopping without any information in the log.
I can be up for some days and the just stop without any information.

I got --restart=unless-stopped on

**Comment by wader** [comment]
Strange, some ideas:
- Any information if you inspect the exited container, exit code etc?
- Modify run script to run with set -x to get more info, maybe see if wait finishes
- Look at dmesg on host if there are segfaulting processes etc
- Enable peer debug in postifx, but this is probably only if the exit is related to some client activity
- Somehow run postfix master with -v
- Modify run script to run postfix in foreground (maybe also with -v somehow)
- Somehow run postfix with strace log

**Comment by wader** [comment]
Keeps stopping?

**Comment by Hamsterman** [comment]
I have been busy the last period so I haven't tested with your new information yet.
But yes it stopped again.

**Comment by Hamsterman** [comment]
It seems that --restart=unless-stopped was set to off for some reason even though my docker run has it included (in my documentation)
Let's assume it's an error at my end.
