### ISSUE TITLE
MX error: host not found

### ISSUE THREAD

**Issue by voryzen** [wader/postfix-relay#23]
hi mwader,

As you're probably aware, peertube uses/suggests your image for their mail/notification work
 
I'm trying to setup my own peertube instance, and have worked through every other issue, however a persistent email error eludes me..
the error is as follows:
`to=<REDACTED@gmail.com>, relay=none, delay=0.11, delays=0.08/0.03/0/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=gmail.com type=MX: Host not found, try again`

the email address is usable, accessed regularly (though redacted for this issue); I'm just curious, if there's fix for this.. if there's something I'm doing wrong.. any help is appreciated

**Comment by wader** [comment]
Hi, that is strange. Can you `docker exec` into the container and use `nslookup` or `host` to see if you can lookup the MX record? might have to install `bind9-host` and  `dnsutil` packages and then do something like `host -v -t mx gmail.com`.

**Comment by voryzen** [comment]
I got `command not found` when trying `nslookup` and `host`..
and I got `unable to locate package` when trying to install `bind9-host` and `dnsutil`

This seems strange to me

**Comment by wader** [comment]
Ah sorry you probably have to do `apt-get update` first, the package source files are removed in the Dockerfile.

**Comment by voryzen** [comment]
nslookup:
root@704fad740233:/app# nslookup gmail.com
Server:         xxx.xxx.xxx.xxx
Address:        xxx.xxx.xxx.xxx#53

Non-authoritative answer:
Name:   gmail.com
Address: 216.xxx.xxx.101
Name:   gmail.com
Address: 2404:xxxx:xxxx:xxx::2005

host -v -t mx gmail.com:
Trying "gmail.com"
(some output, not sure if you wanted it)
Received 27 bytes from 127.0.0.11#53 in 1 ms

**Comment by wader** [comment]
hmm empty MX? i see this:
```
$ host -v -t mx gmail.com
Trying "gmail.com"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18309
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gmail.com.			IN	MX

;; ANSWER SECTION:
gmail.com.		1510	IN	MX	40 alt4.gmail-smtp-in.l.google.com.
gmail.com.		1510	IN	MX	5 gmail-smtp-in.l.google.com.
gmail.com.		1510	IN	MX	30 alt3.gmail-smtp-in.l.google.com.
gmail.com.		1510	IN	MX	20 alt2.gmail-smtp-in.l.google.com.
gmail.com.		1510	IN	MX	10 alt1.gmail-smtp-in.l.google.com.

Received 150 bytes from 192.168.1.1#53 in 4 ms
```

**Comment by wader** [comment]
Or no sorry, no answers at all

**Comment by wader** [comment]
Do you get MX records answers if you do `host -v -t mx gmail.com 8.8.8.8`? you can also try asking your ISP:s DNS server etc, that answer comes from docker:s built in DNS relay

**Comment by wader** [comment]
Does it persist even after a docker daemon restart? does it start to work sometimes without doing anything?

**Comment by voryzen** [comment]
Yes I do get answers when I do `host -v -t mx gmail.com 8.8.8.8`

The error persists after docker restart.. and has never worked

**Comment by voryzen** [comment]
127.0.0.11 is the docker DNS, thats obviously where the issue is

**Comment by wader** [comment]
Does it work to lookup MX on the host that runs docker?

**Comment by voryzen** [comment]
nice work; it doesn't

**Comment by wader** [comment]
Maybe a good test is to lookup MX for some other domains or is this only gmail?

**Comment by voryzen** [comment]
I try a few domains everytime I try the commands, it never works

**Comment by voryzen** [comment]
obviously the issue is with my server setup; I feel like we can close this issue.

Thanks for all the diagnostic help; it's actually been a good learning experience

**Comment by wader** [comment]
Ok! no problem!
