### ISSUE TITLE
Question: how to use Postfix hash: lookup table values?

### ISSUE THREAD

**Issue by kapgit** [wader/postfix-relay#31]
Hi,

I'm trying to setup an email relay which uses the following Postfix 'hash' lookup tables (*):

```
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_generic_maps = hash:/etc/postfix/generic
```

`hash:` values can be set using `POSTFIX_` Docker environment variables, but as the `/etc/postfix` directory is not exposed, I'm not sure how I can call `postmap` to generate the Berkeley DB files which `hash:` expects.

I tried to replace `hash:<BerkeleyDBfile>` with equivalent `inline:{key=value, key=value, key=value}` but without success :confused:

The `inline:` lookup seems supported as reported by

```
docker exec <container_id> postconf -m
btree
cidr
environ
fail
hash
inline
internal
memcache
nis
pipemap
proxy
randmap
regexp
socketmap
static
tcp
texthash
unionmap
unix
```

I guess the easiest would be to expose the `/etc/postfix` directory as a Docker volume?

(*) For reference, I'm following the guide at https://www.linode.com/docs/guides/postfix-smtp-debian7/

Thanks a lot,

Pete

**Comment by wader** [comment]
Hi, can you give some more details like error messages or what is not working? sorry i'm not really a postfix expert

I've tried this and it seems to work:
```sh
docker run --rm -e 'POSTFIX_alias_maps=inline:{a=1,b=2,c=3}'  mwader/postfix-relay
```

Then check if it got configured inside the container:
```sh
root@261ea78f933b:/# postconf | grep -E ^alias_maps
alias_maps = inline:{a=1,b=2,c=3}
```

To expose (volume mount) files in `/etc/postfix` you probably have to volume mount exact path and not the whole `/etc/postfix` directory. Or you just put the files somewhere else.

**Comment by kapgit** [comment]
Hi,

Thanks a lot for your quick reply.

When trying to reproduce and document the problem, I found that `inline:` was actually working fine, and that my configuration values were wrong. They would have been correct for an instance of Postfix running on the host, but not when running inside the container.
I corrected the values and now the container is relaying mails to the external SMTP server as expected. Great!

Just a quick question about your note

> To expose (volume mount) files in `/etc/postfix` you probably have to volume mount exact path and not the whole `/etc/postfix` directory. Or you just put the files somewhere else.

I not sure I understand this. Could you please elaborate?

Thanks again,

Pete

**Comment by wader** [comment]
Sure, if you would do `-v /path/on/host:/etc/postfix` i'm not sure what would happen as there are other postfix config files in that directory and also the container will write to it during startup to convert `POSTFIX_*` variables to configuration. So if you want to have hash files somewhere i would recommend to either put them somewhere else or use full file path volume mount `-v /path/to/hash/file:/etc/postfix/hashfile`.

**Comment by wader** [comment]
Did you get it working? Close issue?

**Comment by kapgit** [comment]
Sorry for my late answer. Your explanation is clear, thank you. Also, thank you for the work you put in this image. A real timesaver! :) 
Actually, as the `inline:` lookups work as expected now, I did not investigate the `/etc` route any further, so we can close this issue.

Thanks again,
Pete

**Comment by wader** [comment]
No problem, good to hear! 👍
