### ISSUE TITLE
Lot to TXT file

### ISSUE THREAD

**Issue by matt-benett** [wader/postfix-relay#4]
Is it possible to enable through Envt variable to make it so I can lot to STDOUT **and** a rolling LOG file.

With SMTP relaying/troubleshooting keeping a history in a plan LOG file is always handy.

**Comment by wader** [comment]
Hi, not at the moment. Probably need to configure rsyslog to do that.

Would it be possible for you to use the docker log features instead? for example make dockerd log to the host syslog and let log rotation etc happen there.

**Comment by wader** [comment]
Closing, please reopen or comment if you come up with some solution
