### ISSUE TITLE
Feature request: add rsyslogd include

### ISSUE THREAD

**Issue by zerkms** [wader/postfix-relay#58]
Would it be possible to add

```
$IncludeConfig /etc/rsyslog.d/*.conf
```

as a first line in the `/etc/rsyslog.conf`?

This would make it possible to configure rsyslogd to needs (eg configure dropping some types of unneeded messages).

It could go right here (as a beginning of this block): https://github.com/wader/postfix-relay/blob/94e0e66dd9f8eb30705270715a55ce5e65e23d07/run#L78-L82

**Comment by wader** [comment]
Hi, yeah that sounds resonable. Maybe it should be last to make it possible to override the default? would it even make sense to make it a env variable that is default `/etc/rsyslog.d/*.conf`?

Want to do a PR?

**Comment by zerkms** [comment]
> Maybe it should be last to make it possible to override the default?

In my local setup I initially have put it as a last line, but apparently `*.*;auth,authpriv.none /dev/stdout` matches everything, so then it's too late to discard messages in the `rsyslog.d` (because it was already accepted by default). So it should be anywhere but before the `*.*` or that line should be changed to be less permissive (but I'm not sure how to do that, from the other hand I'm not an rsyslogd guru either).

> would it even make sense to make it a env variable that is default /etc/rsyslog.d/*.conf?

Possibly, I don't mind. That path is by default in all setups though, so it would be a pretty exotic case to use something else. How about I do a PR with that hardcoded, and if ever anybody asks it to be parameterised - it would be an easy backwards-compatible change, but I bet a cup of coffee that will never happen :-)

> Want to do a PR?

Absolutely :-)

**Comment by wader** [comment]
> > Maybe it should be last to make it possible to override the default?
> 
> In my local setup I initially have put it as a last line, but apparently `*.*;auth,authpriv.none /dev/stdout` matches everything, so then it's too late to discard messages in the `rsyslog.d` (because it was already accepted by default). So it should be anywhere but before the `*.*` or that line should be changed to be less permissive (but I'm not sure how to do that, from the other hand I'm not an rsyslogd guru either).

Aha i see

> > would it even make sense to make it a env variable that is default /etc/rsyslog.d/*.conf?
> 
> Possibly, I don't mind. That path is by default in all setups though, so it would be a pretty exotic case to use something else. How about I do a PR with that hardcoded, and if ever anybody asks it to be parameterised - it would be an easy backwards-compatible change, but I bet a cup of coffee that will never happen :-)

Yeah you convinced, let's do hardcoded 👍 

> > Want to do a PR?
> 
> Absolutely :-)

Great! and some documentation in README.md would good also
