### ISSUE TITLE
Not getting the whole FQDN thing

### ISSUE THREAD

**Issue by falconmick** [wader/postfix-relay#6]
Hi Sorry for more of a Mail question in general than the one to this repo.

When I get to the part for the docker-compose.yml of:

```
  environment:
    - POSTFIX_myhostname=smtp.domain.tld
    - OPENDKIM_DOMAINS=smtp.domain.tld
```

I have no idea what myhostname should be nor any extra DNS setup I will need to do.

Basically I have a Wordpress services running in docker and the mail is becoming a big pain due to sendmail not being the most strait forward thing ever.

If I have the domain: awesomesite.com and I want to send emails from it, what would those settings end up being? do I need to prepend smtp. to awesomesite.com and create an A record??

My site already has a Google inbox so I can't mess with the mx records.

Cheers,
Michael.

**Comment by wader** [comment]
Hi!, for `myhostname` i don't think it is that important. But maybe good that it resolves to the source IP which will be used when connecting to other SMTP server when sending mail. What might be more important now a days is to setup SPF records for your domain.

For how to connect to the SMTP relay i would strongly suggest you use docker networks somehow. Simples is probably to use one docker-compose config that has both a wordpress and postfix-relay service as then docker-compose will create a "default" network between them so they can communicate. Then wordpress should be able to reach the SMTP relay using normal DNS. For example if you have "smtp" service then wordpress should be able to use "smtp" as hostname for it's SMTP server. See https://github.com/wader/postfix-relay#using-docker-compose

**Comment by wader** [comment]
I just noticed POSTFIX_sendingemailfromhere.com.au=smtp.sendingemailfromhere.com.au in your example. Just to be clear, postfix has a config option named ”myhostname” so you should not expand it as a variable etc.

**Comment by falconmick** [comment]
Yeah I litterally just figured that out!

**Comment by wader** [comment]
Aha good 👍 yeah that option is named a bit weirdly. So hostname works now?

**Comment by falconmick** [comment]
Yeah sure does

**Comment by wader** [comment]
Can close?

I did a change to make this more clear https://github.com/wader/postfix-relay/commit/840a28d539cd200b23887e24cac06d2e707e2406 Thanks for bringing this up!

**Comment by falconmick** [comment]
Cheers no problem you can close, thanks for the clarification
