### ISSUE TITLE
[Feature Req] Authentication for clients using Relay

### ISSUE THREAD

**Issue by MeCJay12** [wader/postfix-relay#69]
I've been using this container for a while and I love the simplicity of configuration. I now need to expand the scope of my relay to some moderately trusted networks where explicit trust isn't the best policy. I'm going to fork the repo (https://github.com/MeCJay12/postfix-relay-sasldb), try to work through adding sasldb for basic file backed auth, then submit it for a pull req. Just wanted to open this ticket to track any knowledge gained and to check if there is any existing progress.

**Comment by wader** [comment]
Hey, sounds good 👍 and I don't know of anyone else working on it

**Comment by MeCJay12** [comment]
Closing in favor of comments on the pull request.

https://github.com/wader/postfix-relay/pull/70
