### ISSUE TITLE
452 4.3.1 Insufficient system storage 

### ISSUE THREAD

**Issue by rajmanglani** [wader/postfix-relay#7]
Running docker container on a ubuntu VM. Forwarded port 25 from docker container to VM and then telnet to port 25. Throws insufficient system storage error while entering command "mail from:". I did se the mailbox size limit to 0 as an environment variable. Please help!

**Comment by wader** [comment]
Hello! where do you see that the mailbox size limit is 0? do you set any env variables yourself?

Another possibility might be that one of the `/var` directories used postfix is on a mount that is full. See https://github.com/wader/postfix-relay/blob/master/Dockerfile#L28 for paths. If so maybe make sure those paths are on a host or anonymous volume with free space instead (docker-compose usually do this automatically i think)

**Comment by weiyuchen** [comment]
hello, I'm confusing that the postfix do not save the mail I send, I run docker with "-v /var/mail:/var/mail", but when I telnet to port 25 and send mail to root, it doesn't save anything to /var/mail either in host or in container. Can you help me?

> Hello! where do you see that the mailbox size limit is 0? do you set any env variables yourself?
> 
> Another possibility might be that one of the `�/var` directories used postfix is on a mount that is full. See https://github.com/wader/postfix-relay/blob/master/Dockerfile#L28 for paths. If so maybe make sure those paths are on a host or anonymous volume with free space instead (docker-compose usually do this automatically i think)

**Comment by wader** [comment]
Hi, not sure i follow what you want to do. Your looking for where postfix stores it's queue? (seems to be `/var/spool/postfix`). `/var/mail` seems to be where it delivers local mail. This docker images is mostly for relying mail to other smtp servers and not for local delivery. Maybe it's possible to configure it to do local delivery but i haven't thought about that.

**Comment by weiyuchen** [comment]
thank you for replying me, I tried yesterday and still confused. I'd like to explain my work in detail.

**Comment by weiyuchen** [comment]
> Hi, not sure i follow what you want to do. Your looking for where postfix stores it's queue? (seems to be `/var/spool/postfix`). `/var/mail` seems to be where it delivers local mail. This docker images is mostly for relying mail to other smtp servers and not for local delivery. Maybe it's possible to configure it to do local delivery but i haven't thought about that.

thank you for replying me, I tried yesterday and still confused. I'd like to explain my work in detail.

**Comment by weiyuchen** [comment]
> Hi, not sure i follow what you want to do. Your looking for where postfix stores it's queue? (seems to be `/var/spool/postfix`). `/var/mail` seems to be where it delivers local mail. This docker images is mostly for relying mail to other smtp servers and not for local delivery. Maybe it's possible to configure it to do local delivery but i haven't thought about that.

I want to set a open-relay postfix server. I set the configuration as follow:
`POSTFIX_myhostname=wei.com \
  POSTFIX_mydestination= \
  POSTFIX_mynetworks=0.0.0.0/0 \
  POSTFIX_smtp_tls_security_level=may \
  POSTFIX_smtpd_tls_security_level=none`
the difference is the "mydestination" parameter, because I want use it as a open relay

**Comment by weiyuchen** [comment]
> Hi, not sure i follow what you want to do. Your looking for where postfix stores it's queue? (seems to be `/var/spool/postfix`). `/var/mail` seems to be where it delivers local mail. This docker images is mostly for relying mail to other smtp servers and not for local delivery. Maybe it's possible to configure it to do local delivery but i haven't thought about that.

I really achieve the target, it can deliver mail to my other mailbox though it doesn't have real domain. but I can't find the mail the postfix deferred, even the mail is local delivery

**Comment by weiyuchen** [comment]
> Hi, not sure i follow what you want to do. Your looking for where postfix stores it's queue? (seems to be `/var/spool/postfix`). `/var/mail` seems to be where it delivers local mail. This docker images is mostly for relying mail to other smtp servers and not for local delivery. Maybe it's possible to configure it to do local delivery but i haven't thought about that.

I hope that I have made my problem clear, please help me!

**Comment by wader** [comment]
Hmm still not sure i follow. What do you mean by open relay? the default configuration is an SMTP server that allow you to send to any domain and does not do any local delivery and the fileystem is only used for storing the queue.

Maybe easier if you describe your use case?

**Comment by wader** [comment]
Not sure if this is related to "452 4.3.1 Insufficient system storage"? new issue?

**Comment by wader** [comment]
Closing, please comment if you have more info
